spring.application.name: soap-ws-employee-v1

application:
  http-client:
    employee-api:
      name: srv-neg-employee-configuration-v1
      url: http://localhost:8081

spring:
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
